-- ============================================================================
-- 010_reference_tables.sql
-- TASK-003: Reference tables (PRD section 6) for the ECU Service Lab schema.
--
-- Creates, in dependency order:
--   PRICE_TIER          - fixed price grid ($100/$200/$300/$400)
--   MODULE_CATEGORY      - Airbag/SRS, ECM/PCM, TCM/TCU, BCM, Instrument Cluster
--   VEHICLE_REF           - Make/Model/Year combinations
--   SERVICE               - services offered per module category
--   COMPATIBILITY_ENTRY   - a confirmed Part Number for a vehicle+category
--   COMPATIBILITY_SERVICE - which services are confirmed supported for an entry
--
-- Run via SQL Workshop -> SQL Scripts (or SQLcl) against an empty schema.
-- Safe to re-run only after a DROP; this script does not use IF NOT EXISTS
-- guards, matching the "applied once, in order, on an empty schema" model
-- described in database/install.sql.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- PRICE_TIER
-- Fixed price grid. TIER_CODE is the tier's own natural key ('100'/'200'/
-- '300'/'400'), not a surrogate id, since SERVICE.PRICE_TIER references it
-- directly by that code (PRD section 6: SERVICE.PRICE_TIER VARCHAR2(10)).
-- ----------------------------------------------------------------------------
CREATE TABLE price_tier (
    tier_code   VARCHAR2(10)    NOT NULL,
    amount      NUMBER(10,2)    NOT NULL,
    CONSTRAINT pk_price_tier PRIMARY KEY (tier_code),
    CONSTRAINT ck_price_tier_amount CHECK (amount > 0)
);

COMMENT ON TABLE price_tier IS 'Fixed price grid ($100/$200/$300/$400). Admin-editable amounts; SERVICE.PRICE_TIER FKs to TIER_CODE.';

-- ----------------------------------------------------------------------------
-- MODULE_CATEGORY
-- Airbag/SRS, ECM/PCM, TCM/TCU, BCM, Instrument Cluster (PRD 4.1).
-- ----------------------------------------------------------------------------
CREATE TABLE module_category (
    category_id     NUMBER          GENERATED BY DEFAULT AS IDENTITY
                                     (START WITH 1 INCREMENT BY 1) NOT NULL,
    name            VARCHAR2(50)    NOT NULL,
    display_seq     NUMBER(4)       DEFAULT 10 NOT NULL,
    CONSTRAINT pk_module_category PRIMARY KEY (category_id),
    CONSTRAINT uq_module_category_name UNIQUE (name)
);

COMMENT ON TABLE module_category IS 'Module categories: Airbag/SRS, ECM/PCM, TCM/TCU, BCM, Instrument Cluster.';
COMMENT ON COLUMN module_category.display_seq IS 'Ordering hint for the f92606 category radio group (TASK-016).';

-- ----------------------------------------------------------------------------
-- VEHICLE_REF
--
-- DDL DECISION (per TASK-003 acceptance criteria, "one VEHICLE_ID per year,
-- or a YEAR_FROM/YEAR_TO range"): this schema uses ONE VEHICLE_ID PER YEAR
-- (PRD section 6's literal VEHICLE_REF shape: MAKE, MODEL, YEAR NUMBER(4) --
-- no YEAR_FROM/YEAR_TO columns given), not a year range.
--
-- Rationale:
--   - COMPATIBILITY_ENTRY's exact-match lookup (TASK-013: find_match by
--     vehicle_id + category_id + part_number, "never a LIKE or fuzzy match")
--     is simplest and least error-prone against a single YEAR value: a range
--     would force either a second BETWEEN-based lookup path (contradicting
--     "never a LIKE or fuzzy match" in spirit) or a range-to-per-year
--     expansion at import time anyway.
--   - The bulk import (TASK-044) already normalizes external supported-
--     module lists row by row; expanding a "2015-2019" source range into
--     five VEHICLE_REF rows at import time is a one-line MERGE loop and
--     keeps every other package (pkg_compat, v_vehicle_lov, the f92606
--     cascading LOVs) working against plain equality.
--   - A UNIQUE constraint on (MAKE, MODEL, YEAR) prevents duplicate vehicle
--     rows, which a range model would need a separate overlap-detection
--     rule for.
-- ----------------------------------------------------------------------------
CREATE TABLE vehicle_ref (
    vehicle_id  NUMBER          GENERATED BY DEFAULT AS IDENTITY
                                 (START WITH 1 INCREMENT BY 1) NOT NULL,
    make        VARCHAR2(50)    NOT NULL,
    model       VARCHAR2(50)    NOT NULL,
    year        NUMBER(4)       NOT NULL,
    CONSTRAINT pk_vehicle_ref PRIMARY KEY (vehicle_id),
    CONSTRAINT uq_vehicle_ref UNIQUE (make, model, year),
    CONSTRAINT ck_vehicle_ref_year CHECK (year BETWEEN 1980 AND 2100)
);

COMMENT ON TABLE vehicle_ref IS 'Make/Model/Year combinations. One row per model year (see DDL decision comment above) -- not a YEAR_FROM/YEAR_TO range.';

-- ----------------------------------------------------------------------------
-- SERVICE
-- Services offered per module category, each mapped to a fixed price tier
-- and a QUESTION_SET_CODE that drives the dynamic questions in TASK-020.
-- ----------------------------------------------------------------------------
CREATE TABLE service (
    service_id          NUMBER          GENERATED BY DEFAULT AS IDENTITY
                                         (START WITH 1 INCREMENT BY 1) NOT NULL,
    category_id         NUMBER          NOT NULL,
    name                VARCHAR2(100)   NOT NULL,
    price_tier          VARCHAR2(10)    NOT NULL,
    question_set_code   VARCHAR2(30)    NOT NULL,
    needs_follow_up     VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_service PRIMARY KEY (service_id),
    CONSTRAINT fk_service_category FOREIGN KEY (category_id)
        REFERENCES module_category (category_id),
    CONSTRAINT fk_service_price_tier FOREIGN KEY (price_tier)
        REFERENCES price_tier (tier_code),
    CONSTRAINT ck_service_follow_up CHECK (needs_follow_up IN ('Y', 'N'))
);

COMMENT ON TABLE service IS 'Services offered per module category (e.g. Crash Data Reset, Cloning, VIN Write), each with a fixed price tier and a dynamic question set.';
COMMENT ON COLUMN service.needs_follow_up IS 'Y if this service should show the "will you need post-install follow-up work" question (PRD 4.4).';

CREATE INDEX ix_service_category ON service (category_id);

-- ----------------------------------------------------------------------------
-- COMPATIBILITY_ENTRY
-- A confirmed Part Number for a given vehicle + module category. The unique
-- index on (vehicle_id, category_id, part_number) both enforces one entry
-- per combination and IS the exact-match lookup index used by
-- pkg_compat.find_match (TASK-013).
-- ----------------------------------------------------------------------------
CREATE TABLE compatibility_entry (
    entry_id        NUMBER          GENERATED BY DEFAULT AS IDENTITY
                                     (START WITH 1 INCREMENT BY 1) NOT NULL,
    vehicle_id      NUMBER          NOT NULL,
    category_id     NUMBER          NOT NULL,
    part_number     VARCHAR2(100)   NOT NULL,
    photo_hint      BLOB,
    source          VARCHAR2(20)    NOT NULL,
    created_at      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_compatibility_entry PRIMARY KEY (entry_id),
    CONSTRAINT fk_compat_entry_vehicle FOREIGN KEY (vehicle_id)
        REFERENCES vehicle_ref (vehicle_id),
    CONSTRAINT fk_compat_entry_category FOREIGN KEY (category_id)
        REFERENCES module_category (category_id)
    -- CK_COMPAT_ENTRY_SOURCE (SOURCE IN ('IMPORT','ADMIN_CONFIRMED')) is added
    -- in 040_constraints.sql (TASK-006), which owns all CHECK constraints.
);

COMMENT ON TABLE compatibility_entry IS 'A confirmed Part Number for a vehicle + module category. SOURCE tracks provenance (IMPORT vs ADMIN_CONFIRMED). PART_NUMBER is normalized to UPPER(TRIM()) by a BEFORE INSERT/UPDATE trigger (TASK-006).';
COMMENT ON COLUMN compatibility_entry.photo_hint IS 'Optional: where the module sits / what it looks like (PRD 5.3). Populated via pkg_security.store_* (TASK-011) once file-upload wiring exists; nullable until then.';

-- Exact-match lookup index (also enforces uniqueness): pkg_compat.find_match
-- (TASK-013) must never do a LIKE/fuzzy match, so this equality index is the
-- entire lookup path.
CREATE UNIQUE INDEX ux_compat_entry_lookup
    ON compatibility_entry (vehicle_id, category_id, part_number);

-- ----------------------------------------------------------------------------
-- COMPATIBILITY_SERVICE (junction)
-- Which services are confirmed supported for a given compatibility entry.
-- Composite PK per PRD section 6 / TASK-003 acceptance criteria.
-- ----------------------------------------------------------------------------
CREATE TABLE compatibility_service (
    entry_id    NUMBER  NOT NULL,
    service_id  NUMBER  NOT NULL,
    CONSTRAINT pk_compatibility_service PRIMARY KEY (entry_id, service_id),
    CONSTRAINT fk_compat_service_entry FOREIGN KEY (entry_id)
        REFERENCES compatibility_entry (entry_id) ON DELETE CASCADE,
    CONSTRAINT fk_compat_service_service FOREIGN KEY (service_id)
        REFERENCES service (service_id)
);

COMMENT ON TABLE compatibility_service IS 'Junction: which SERVICE rows are confirmed supported for a given COMPATIBILITY_ENTRY. An entry with zero rows here counts as "no match" per pkg_compat.find_match (TASK-013).';

CREATE INDEX ix_compat_service_service ON compatibility_service (service_id);
