-- ============================================================================
-- 020_order_tables.sql
-- TASK-004: Order tables (PRD section 6) for the ECU Service Lab schema.
--
-- Creates: ORDERS, ORDER_PHOTO, ORDER_ANSWER, ORDER_STATUS_HISTORY.
-- Depends on 010_reference_tables.sql (VEHICLE_REF, MODULE_CATEGORY,
-- COMPATIBILITY_ENTRY, SERVICE).
--
-- Run via SQL Workshop -> SQL Scripts (or SQLcl) against a schema that
-- already has 010_reference_tables.sql applied.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- ORDERS
--
-- Every field from PRD section 6's ORDERS table, plus two fields the PRD
-- data model didn't explicitly list but that later tasks require:
--   - RETURN_TRACKING_NO   (needed by email #4, TASK-029/037)
--   - IDEMPOTENCY_KEY      (unique; pkg_order.submit_order, TASK-015, uses it
--                           to make a repeated submit return the existing
--                           order instead of creating a duplicate)
--
-- STATUS/PHOTO_TYPE/etc. CHECK constraints are added in 040_constraints.sql
-- (TASK-006), not here -- see the "validation in layers" note in
-- agent_instructions.during_work and the same pattern used in
-- 010_reference_tables.sql.
-- ----------------------------------------------------------------------------
CREATE TABLE orders (
    order_id                NUMBER          GENERATED BY DEFAULT AS IDENTITY
                                             (START WITH 1 INCREMENT BY 1) NOT NULL,
    tracking_token           VARCHAR2(64)    NOT NULL,
    status                   VARCHAR2(30)    NOT NULL,
    vehicle_id               NUMBER          NOT NULL,
    category_id              NUMBER          NOT NULL,
    part_number_entered      VARCHAR2(100)   NOT NULL,
    matched_entry_id         NUMBER,
    service_id               NUMBER,
    description               CLOB           NOT NULL,
    customer_name             VARCHAR2(200)  NOT NULL,
    customer_email             VARCHAR2(320) NOT NULL,
    customer_phone             VARCHAR2(30)  NOT NULL,
    return_address_street      VARCHAR2(200) NOT NULL,
    return_address_city        VARCHAR2(100) NOT NULL,
    return_address_state       VARCHAR2(2)   DEFAULT 'HI' NOT NULL,
    return_address_zip         VARCHAR2(10)  NOT NULL,
    service_price               NUMBER(10,2),
    return_shipping_fee         NUMBER(10,2),
    total_amount                 NUMBER(10,2),
    stripe_payment_link_id        VARCHAR2(100),
    stripe_payment_status          VARCHAR2(30),
    return_tracking_no             VARCHAR2(100),
    idempotency_key                 VARCHAR2(100)  NOT NULL,
    shipping_label                   BLOB,
    created_at                        TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at                        TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (order_id),
    CONSTRAINT uq_orders_tracking_token UNIQUE (tracking_token),
    CONSTRAINT uq_orders_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT fk_orders_vehicle FOREIGN KEY (vehicle_id)
        REFERENCES vehicle_ref (vehicle_id),
    CONSTRAINT fk_orders_category FOREIGN KEY (category_id)
        REFERENCES module_category (category_id),
    CONSTRAINT fk_orders_matched_entry FOREIGN KEY (matched_entry_id)
        REFERENCES compatibility_entry (entry_id),
    CONSTRAINT fk_orders_service FOREIGN KEY (service_id)
        REFERENCES service (service_id)
);

COMMENT ON TABLE orders IS 'One row per customer order (guest checkout, no accounts). STATUS drives the fulfillment lifecycle (pkg_order_status, TASK-012). PART_NUMBER_ENTERED is normalized to UPPER(TRIM()) by a BEFORE INSERT/UPDATE trigger (TASK-006).';
COMMENT ON COLUMN orders.tracking_token IS 'Cryptographically random, non-sequential token (pkg_security.generate_tracking_token, TASK-011) -- the only credential needed to view the public tracking page. Never the numeric ORDER_ID.';
COMMENT ON COLUMN orders.matched_entry_id IS 'Set once a COMPATIBILITY_ENTRY is matched (auto at submission, or admin-confirmed via pkg_review, TASK-040). NULL while status = Pending Review.';
COMMENT ON COLUMN orders.service_id IS 'NULL until a service is selected/confirmed. Matched path: set at submission. Pending Review path: set only once pkg_review.confirm_compatibility runs (TASK-040).';
COMMENT ON COLUMN orders.service_price IS 'Snapshot of PRICE_TIER.AMOUNT at the time pkg_pricing (TASK-014) priced this order -- NOT a live join to PRICE_TIER, so later tier-amount edits never retroactively change this order (PRD 5.4 acceptance criteria).';
COMMENT ON COLUMN orders.return_shipping_fee IS 'Snapshot of APP_SETTING''s return-shipping value at order time, same non-retroactive rule as SERVICE_PRICE.';
COMMENT ON COLUMN orders.total_amount IS 'SERVICE_PRICE + RETURN_SHIPPING_FEE, snapshotted together by pkg_pricing (TASK-014). NULL until priced (i.e. while still Pending Review with no confirmed service).';
COMMENT ON COLUMN orders.return_tracking_no IS 'Carrier tracking number for the return shipment, entered by the admin when moving an order to Ready / Shipped Back (TASK-037) and included in email #4 (TASK-029).';
COMMENT ON COLUMN orders.idempotency_key IS 'Generated client-side when the review/submit page (f92606 Page 15, TASK-022) loads; pkg_order.submit_order (TASK-015) uses it so a repeated/duplicate submit returns the existing order instead of inserting a second one.';
COMMENT ON COLUMN orders.shipping_label IS 'Optional: a return shipping label the admin attaches once ready to ship back (TASK-038). NULL if none was attached -- the confirmation flow simply omits that piece (PRD section 8).';
COMMENT ON COLUMN orders.stripe_payment_link_id IS 'Set by pkg_stripe.create_payment_link (TASK-030) on the transition to Awaiting Payment. NULL until then.';
COMMENT ON COLUMN orders.stripe_payment_status IS 'Mirrors the Stripe payment link''s status; updated by the ORDS webhook handler (TASK-032/033).';

-- Future shipping-API integration point (PRD section 7's "Integration points
-- to build against" and section 8's "design note for future-proofing"):
-- when a real rate/label API (e.g. EasyPost/Shippo) is added post-MVP, add
--   SHIPPING_PROVIDER    VARCHAR2(30)   -- e.g. 'EASYPOST', 'SHIPPO'
--   EXTERNAL_LABEL_ID    VARCHAR2(100)  -- the provider's label/shipment id
-- as nullable columns here. Not created now (out of v1 scope, PRD section 11)
-- -- RETURN_SHIPPING_FEE stays a flat snapshot value in the meantime, exactly
-- as the PRD's design note specifies.

-- Admin search indexes (PRD 5.1: "admin can find any order within a couple
-- of clicks by email, order number, or Part Number").
CREATE INDEX ix_orders_email_lower ON orders (LOWER(customer_email));
CREATE INDEX ix_orders_status ON orders (status);
CREATE INDEX ix_orders_vehicle ON orders (vehicle_id);
CREATE INDEX ix_orders_category ON orders (category_id);
CREATE INDEX ix_orders_matched_entry ON orders (matched_entry_id);
CREATE INDEX ix_orders_service ON orders (service_id);

-- ----------------------------------------------------------------------------
-- ORDER_PHOTO
-- Sticker/label photo (required at submission), plus DONOR/ORIGINAL photos
-- for cloning orders (PRD 4.4).
-- ----------------------------------------------------------------------------
CREATE TABLE order_photo (
    photo_id      NUMBER          GENERATED BY DEFAULT AS IDENTITY
                                   (START WITH 1 INCREMENT BY 1) NOT NULL,
    order_id      NUMBER          NOT NULL,
    photo_type    VARCHAR2(20)    NOT NULL,
    photo_blob    BLOB            NOT NULL,
    uploaded_at   TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_order_photo PRIMARY KEY (photo_id),
    CONSTRAINT fk_order_photo_order FOREIGN KEY (order_id)
        REFERENCES orders (order_id) ON DELETE CASCADE
    -- CK_ORDER_PHOTO_TYPE (PHOTO_TYPE IN ('STICKER','DONOR','ORIGINAL')) is
    -- added in 040_constraints.sql (TASK-006).
);

COMMENT ON TABLE order_photo IS 'Photos uploaded for an order: STICKER (the required label photo), DONOR/ORIGINAL (cloning orders, PRD 4.4). Populated via pkg_security.store_order_photo (TASK-011) from APEX_APPLICATION_TEMP_FILES.';

CREATE INDEX ix_order_photo_order ON order_photo (order_id);

-- ----------------------------------------------------------------------------
-- ORDER_ANSWER
-- Answers to the dynamic, service-driven question set (PRD 4.4 / TASK-020).
-- ----------------------------------------------------------------------------
CREATE TABLE order_answer (
    answer_id       NUMBER          GENERATED BY DEFAULT AS IDENTITY
                                     (START WITH 1 INCREMENT BY 1) NOT NULL,
    order_id        NUMBER          NOT NULL,
    question_code   VARCHAR2(50)    NOT NULL,
    answer_value    VARCHAR2(4000),
    CONSTRAINT pk_order_answer PRIMARY KEY (answer_id),
    CONSTRAINT fk_order_answer_order FOREIGN KEY (order_id)
        REFERENCES orders (order_id) ON DELETE CASCADE,
    CONSTRAINT uq_order_answer_question UNIQUE (order_id, question_code)
);

COMMENT ON TABLE order_answer IS 'One row per (order, question_code) answer to the dynamic question set defined by QUESTION_DEF (TASK-005) for the order''s selected service''s QUESTION_SET_CODE.';

CREATE INDEX ix_order_answer_order ON order_answer (order_id);

-- ----------------------------------------------------------------------------
-- ORDER_STATUS_HISTORY
-- Full audit trail of every status change, written exclusively by
-- pkg_order_status (TASK-012).
-- ----------------------------------------------------------------------------
CREATE TABLE order_status_history (
    history_id    NUMBER          GENERATED BY DEFAULT AS IDENTITY
                                   (START WITH 1 INCREMENT BY 1) NOT NULL,
    order_id      NUMBER          NOT NULL,
    status        VARCHAR2(30)    NOT NULL,
    changed_at    TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    changed_by    VARCHAR2(50)    NOT NULL,
    CONSTRAINT pk_order_status_history PRIMARY KEY (history_id),
    CONSTRAINT fk_order_status_history_order FOREIGN KEY (order_id)
        REFERENCES orders (order_id) ON DELETE CASCADE
);

COMMENT ON TABLE order_status_history IS 'Append-only audit trail of ORDERS.STATUS transitions. CHANGED_BY is the admin username (APP_USER), or SYSTEM for webhook/automated transitions. Written only by pkg_order_status.change_status (TASK-012); a trigger on ORDERS (TASK-006) rejects any STATUS change that does not go through that package.';

CREATE INDEX ix_order_status_history_order ON order_status_history (order_id, changed_at);
