-- ============================================================================
-- 030_config_and_logs.sql
-- TASK-005: Configuration, dynamic-question and technical-log tables
-- (PRD section 6 + operational needs of later tasks).
--
-- Creates: APP_SETTING, QUESTION_DEF, EMAIL_LOG, STRIPE_EVENT, APP_ERROR_LOG.
-- Depends on 020_order_tables.sql (EMAIL_LOG and STRIPE_EVENT FK to ORDERS).
--
-- Run via SQL Workshop -> SQL Scripts (or SQLcl) against a schema that
-- already has 010_reference_tables.sql and 020_order_tables.sql applied.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- APP_SETTING
-- Simple key/value store for the small set of admin-configurable values
-- referenced across the app (PRD 5.4, 7, 9). Not a general-purpose config
-- table -- every key this app actually reads is seeded in TASK-008 and
-- listed below for reference.
-- ----------------------------------------------------------------------------
CREATE TABLE app_setting (
    setting_key     VARCHAR2(50)    NOT NULL,
    setting_value   VARCHAR2(4000)  NOT NULL,
    description     VARCHAR2(200),
    updated_at      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_app_setting PRIMARY KEY (setting_key)
);

COMMENT ON TABLE app_setting IS 'Admin-configurable key/value settings. Known keys (seeded in TASK-008): RETURN_SHIPPING_FEE (pkg_pricing.get_return_fee, TASK-014; PRD 5.4: 20-30 range), ADMIN_EMAIL (pkg_notify email #5 recipient, TASK-028), MAIL_FROM (APEX_MAIL sender, TASK-027), APP_BASE_URL (used to build the public tracking link emailed to customers, TASK-028).';
COMMENT ON COLUMN app_setting.setting_value IS 'Always stored as text; callers (pkg_pricing, pkg_notify) are responsible for their own TO_NUMBER/casting.';

-- ----------------------------------------------------------------------------
-- QUESTION_DEF
-- Drives the dynamic, service-specific question set on f100 Page 13
-- (PRD 4.4 / TASK-020). Data-driven by design: adding a new QUESTION_SET_CODE
-- with its own rows needs no new page.
-- ----------------------------------------------------------------------------
CREATE TABLE question_def (
    question_set_code  VARCHAR2(30)    NOT NULL,
    question_code       VARCHAR2(50)   NOT NULL,
    label                 VARCHAR2(500) NOT NULL,
    answer_type            VARCHAR2(20) NOT NULL,
    is_required              VARCHAR2(1) DEFAULT 'Y' NOT NULL,
    display_seq                NUMBER(4) DEFAULT 10 NOT NULL,
    CONSTRAINT pk_question_def PRIMARY KEY (question_set_code, question_code),
    CONSTRAINT ck_question_def_required CHECK (is_required IN ('Y', 'N'))
    -- CK_QUESTION_DEF_ANSWER_TYPE (ANSWER_TYPE IN ('TEXT','YES_NO','TEXTAREA',
    -- 'PHOTO')) is added in 040_constraints.sql (TASK-006), matching the
    -- layering used for every other domain-value CHECK in this schema.
);

COMMENT ON TABLE question_def IS 'Dynamic question definitions per QUESTION_SET_CODE (SRS, CLONING, VIN_WRITE, RESTORATION, FOLLOW_UP -- seeded in TASK-008 per PRD 4.4). SERVICE.QUESTION_SET_CODE picks which set of rows renders for a given service (TASK-020).';
COMMENT ON COLUMN question_def.answer_type IS 'TEXT / YES_NO / TEXTAREA / PHOTO -- drives which item type f100 Page 13 renders for this question (TASK-020).';
COMMENT ON COLUMN question_def.is_required IS 'Y if leaving this question blank should fail the page-13 validation (TASK-020).';
COMMENT ON COLUMN question_def.display_seq IS 'Ordering hint for rendering questions within a set.';

-- ----------------------------------------------------------------------------
-- EMAIL_LOG
-- Every attempted send of one of the 5 transactional emails (PRD section 9),
-- so pkg_notify (TASK-027/028/029) can enforce "sent exactly once per order"
-- and never silently swallow a delivery failure.
-- ----------------------------------------------------------------------------
CREATE TABLE email_log (
    email_log_id    NUMBER          GENERATED BY DEFAULT AS IDENTITY
                                     (START WITH 1 INCREMENT BY 1) NOT NULL,
    order_id        NUMBER          NOT NULL,
    email_type       VARCHAR2(30)   NOT NULL,
    recipient          VARCHAR2(320) NOT NULL,
    sent_at              TIMESTAMP  DEFAULT SYSTIMESTAMP NOT NULL,
    result                 VARCHAR2(20) NOT NULL,
    error_text                VARCHAR2(4000),
    CONSTRAINT pk_email_log PRIMARY KEY (email_log_id),
    CONSTRAINT fk_email_log_order FOREIGN KEY (order_id)
        REFERENCES orders (order_id) ON DELETE CASCADE,
    CONSTRAINT ck_email_log_result CHECK (result IN ('SUCCESS', 'FAILED'))
    -- CK_EMAIL_LOG_TYPE, constraining EMAIL_TYPE to the 5 PRD section 9
    -- trigger codes (e.g. ORDER_SUBMITTED / PAYMENT_LINK / MODULE_RECEIVED /
    -- SHIPPED_BACK / ADMIN_NEW_ORDER), is added in 040_constraints.sql
    -- (TASK-006) once pkg_notify (TASK-027) fixes the exact code strings it
    -- will use.
);

COMMENT ON TABLE email_log IS 'One row per attempted transactional-email send (PRD section 9''s 5 triggers). pkg_notify.send (TASK-027) writes here regardless of success/failure and never rolls back the business transaction on an email error; pkg_order/pkg_order_status query this to guarantee each email fires exactly once per order.';
COMMENT ON COLUMN email_log.email_type IS 'Which of the 5 PRD section 9 triggers this was (order submitted, payment link, module received, shipped back, admin new-order alert). Exact code strings are fixed by pkg_notify (TASK-027).';
COMMENT ON COLUMN email_log.result IS 'SUCCESS or FAILED. On FAILED, ERROR_TEXT holds the APEX_MAIL/SMTP error so the admin (or a future agent) can see delivery problems without digging through instance logs.';

CREATE INDEX ix_email_log_order ON email_log (order_id, email_type);

-- ----------------------------------------------------------------------------
-- STRIPE_EVENT
-- Every Stripe webhook event received, keyed by Stripe's own EVENT_ID so a
-- retried/duplicate webhook delivery is a no-op (TASK-033).
-- ----------------------------------------------------------------------------
CREATE TABLE stripe_event (
    stripe_event_id   NUMBER          GENERATED BY DEFAULT AS IDENTITY
                                       (START WITH 1 INCREMENT BY 1) NOT NULL,
    event_id           VARCHAR2(100)  NOT NULL,
    event_type           VARCHAR2(100) NOT NULL,
    order_id                NUMBER,
    payload                   CLOB,
    received_at                 TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    processed                     VARCHAR2(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_stripe_event PRIMARY KEY (stripe_event_id),
    CONSTRAINT uq_stripe_event_event_id UNIQUE (event_id),
    CONSTRAINT fk_stripe_event_order FOREIGN KEY (order_id)
        REFERENCES orders (order_id),
    CONSTRAINT ck_stripe_event_processed CHECK (processed IN ('Y', 'N'))
);

COMMENT ON TABLE stripe_event IS 'One row per Stripe webhook event received via the ORDS endpoint (TASK-032/033). EVENT_ID is Stripe''s own event id (evt_...) and is UNIQUE, so a retried webhook delivery is detected and ignored (idempotency) rather than double-processed.';
COMMENT ON COLUMN stripe_event.order_id IS 'Resolved from the event''s metadata.order_id once the handler looks it up; NULL if the order could not be resolved (logged to APP_ERROR_LOG instead).';
COMMENT ON COLUMN stripe_event.payload IS 'Raw JSON payload, kept for audit/debugging Stripe integration issues. Never contains card data (PCI scope stays entirely on Stripe''s side, PRD section 10).';
COMMENT ON COLUMN stripe_event.processed IS 'Y once pkg_stripe.handle_event has successfully advanced the order''s status for this event; used to short-circuit reprocessing on a duplicate delivery even before the UNIQUE constraint would raise.';

CREATE INDEX ix_stripe_event_order ON stripe_event (order_id);

-- ----------------------------------------------------------------------------
-- APP_ERROR_LOG
-- Generic technical error log for server-side failures that aren't a
-- customer-facing APEX validation message -- primarily Stripe API errors
-- (TASK-030: "API errors are written to APP_ERROR_LOG and raised as readable
-- exceptions") but written to by any package that needs an audit trail for
-- an unexpected failure.
-- ----------------------------------------------------------------------------
CREATE TABLE app_error_log (
    error_id         NUMBER          GENERATED BY DEFAULT AS IDENTITY
                                      (START WITH 1 INCREMENT BY 1) NOT NULL,
    error_at          TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    error_source        VARCHAR2(100) NOT NULL,
    error_message          VARCHAR2(4000) NOT NULL,
    error_backtrace           CLOB,
    order_id                    NUMBER,
    context_info                  VARCHAR2(4000),
    CONSTRAINT pk_app_error_log PRIMARY KEY (error_id),
    CONSTRAINT fk_app_error_log_order FOREIGN KEY (order_id)
        REFERENCES orders (order_id)
);

COMMENT ON TABLE app_error_log IS 'Generic technical error log, e.g. pkg_stripe API failures (TASK-030) or any other unexpected server-side error a package chooses to record before re-raising. Not a substitute for APEX''s own page-level error handling -- for user-facing validation failures.';
COMMENT ON COLUMN app_error_log.error_source IS 'Free-text origin, e.g. "PKG_STRIPE.CREATE_PAYMENT_LINK".';
COMMENT ON COLUMN app_error_log.order_id IS 'Nullable: the related order, when the error happened in an order-specific context (most Stripe/email errors will have one).';

CREATE INDEX ix_app_error_log_order ON app_error_log (order_id);
CREATE INDEX ix_app_error_log_at ON app_error_log (error_at);
