-- ============================================================================
-- 070_import_staging.sql
-- TASK-044: staging table for bulk compatibility imports (pkg_import).
--
-- One row per CSV data row, keyed by (BATCH_ID, ROW_NUM). Every value is
-- staged as raw text exactly as read from the CSV -- no type conversion or
-- lookup happens at INSERT time, only in pkg_import.validate_batch, so a
-- bad row (wrong year format, unknown category, ...) is diagnosable from
-- this table alone rather than failing an INSERT outright. See
-- pkg_import.pks for the full CSV format this table's columns mirror and
-- README.md's "Bulk compatibility import" section for the file-level
-- documentation TASK-044 requires.
--
-- Depends on nothing beyond a working schema (no FKs to VEHICLE_REF/
-- MODULE_CATEGORY/SERVICE/COMPATIBILITY_ENTRY -- a staging row is allowed
-- to reference a category or service that does not exist; that is exactly
-- what VALIDATE_BATCH is for).
-- ----------------------------------------------------------------------------
CREATE TABLE compat_import_stg (
    stg_id              NUMBER          GENERATED BY DEFAULT AS IDENTITY
                                         (START WITH 1 INCREMENT BY 1) NOT NULL,
    batch_id            VARCHAR2(50)    NOT NULL,
    row_num             NUMBER          NOT NULL,
    make_raw            VARCHAR2(200),
    model_raw           VARCHAR2(200),
    year_raw            VARCHAR2(200),
    category_raw        VARCHAR2(200),
    part_number_raw     VARCHAR2(200),
    service_names_raw   VARCHAR2(4000),
    status              VARCHAR2(20)    DEFAULT 'PENDING' NOT NULL,
    error_text          VARCHAR2(4000),
    created_at          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_compat_import_stg PRIMARY KEY (stg_id),
    CONSTRAINT uq_compat_import_stg_row UNIQUE (batch_id, row_num),
    CONSTRAINT ck_compat_import_stg_status
        CHECK (status IN ('PENDING', 'VALID', 'INVALID', 'APPLIED'))
);

COMMENT ON TABLE compat_import_stg IS 'TASK-044 staging area for bulk compatibility CSV imports. One row per CSV data row (BATCH_ID groups a single import run). *_RAW columns hold the CSV values exactly as read, unvalidated -- pkg_import.validate_batch is the only place that interprets/rejects them, so a bad value is always diagnosable here rather than causing an INSERT failure.';
COMMENT ON COLUMN compat_import_stg.batch_id IS 'Generated by pkg_import.start_batch (format IMPB-<timestamp>-<random>) -- groups every row from one import run/CSV file so validate_batch/apply_batch/a preview screen (TASK-045) can operate on "this file" as a unit.';
COMMENT ON COLUMN compat_import_stg.row_num IS '1-based position of this row within its CSV file (header excluded), for error messages/preview ordering that need to point back at "row 7 of the file", not just an opaque STG_ID.';
COMMENT ON COLUMN compat_import_stg.status IS 'PENDING (just staged, not yet validated) -> VALID or INVALID (pkg_import.validate_batch) -> APPLIED (pkg_import.apply_batch, VALID rows only). An INVALID row is never applied; re-running apply_batch on an already-APPLIED batch applies nothing further (no VALID rows remain), so it is safe to call more than once.';
COMMENT ON COLUMN compat_import_stg.error_text IS 'Human-readable validation problem(s) for an INVALID row, or an unexpected runtime error if a VALID row still failed during apply_batch (e.g. a referenced SERVICE was deleted between validation and apply) -- that row is reset to INVALID with this text rather than left half-applied. NULL for PENDING/VALID/successfully-APPLIED rows.';

CREATE INDEX ix_compat_import_stg_batch ON compat_import_stg (batch_id, status);

-- ----------------------------------------------------------------------------
-- TRG_COMPAT_IMPORT_STG_BIU
-- CREATED_AT/UPDATED_AT bookkeeping, same convention as every other
-- TRG_*_BIU trigger in 050_triggers.sql -- defined here instead of there
-- since this table is created after that file already ran in install
-- order (see install.sql: DDL -> ... -> triggers -> views -> import
-- staging), not because the convention itself differs.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_compat_import_stg_biu
    BEFORE INSERT OR UPDATE ON compat_import_stg
    FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.created_at := NVL(:NEW.created_at, SYSTIMESTAMP);
    END IF;
    :NEW.updated_at := SYSTIMESTAMP;
END trg_compat_import_stg_biu;
/
