-- ============================================================================
-- pkg_stripe.pks
-- TASK-030: create a Stripe Payment Link for an order and read it back.
-- TASK-031: create_payment_link now also refuses any order not currently in
-- Awaiting Payment status (see its own comment below) -- no other public
-- signature changed by this task; the payment-gate wiring itself (calling
-- this from pkg_order_status on the transition, and email #2) lives in
-- pkg_order_status.pkb.
-- TASK-032/033: added handle_event -- the single entry point the
-- database/ords/stripe_webhook.sql ORDS module calls for every inbound
-- Stripe webhook delivery. See handle_event's own comment below for the
-- signature-verification / idempotency design (TASK-033) and the event
-- processing itself (TASK-032).
--
-- TASK-033 manual prerequisite, same shape as TASK-030's Web Credential
-- above but for a different reason: Stripe's webhook signing secret
-- (whsec_...) must be usable from PL/SQL to compute an HMAC ourselves (see
-- handle_event), and APEX's Web Credentials are write-only from PL/SQL --
-- APEX_WEB_SERVICE can attach one to an OUTBOUND request via
-- p_credential_static_id, but there is no API to read a Web Credential's
-- secret back out for a computation like this. So, per this task's own
-- acceptance criteria ("Web Credential or protected APP_SETTING"), the
-- webhook secret is instead stored as APP_SETTING.STRIPE_WEBHOOK_SECRET.
-- The row seeded by database/seed/010_reference_data.sql is a PLACEHOLDER
-- value ('whsec_REPLACE_ME') -- an admin must overwrite it with the real
-- signing secret from the Stripe Dashboard (Developers -> Webhooks -> the
-- registered endpoint -> Signing secret) directly in the live table once
-- the ORDS endpoint below is registered and its public URL is known to
-- give Stripe. The real secret is never committed to this repository.
--
-- Manual prerequisite (cannot be done from SQL -- this is exactly why PRD
-- 10 / this task's acceptance criteria require it to live outside code and
-- git in the first place): before this package can be called, a Web
-- Credential must exist in this workspace's Shared Components -> Web
-- Credentials with:
--   Static ID:      STRIPE_SECRET_KEY   (must match c_credential_static_id
--                                        in pkg_stripe.pkb exactly)
--   Auth Type:      HTTP Basic Authentication
--   Username:       the Stripe secret key (sk_test_... in test mode,
--                    sk_live_... in production -- Stripe's own convention
--                    is "API key as the Basic-Auth username, password
--                    blank")
--   Password:       left blank
-- The key itself is never stored in this repository -- pkg_stripe only
-- ever references it by STATIC ID via APEX_WEB_SERVICE's
-- p_credential_static_id, which resolves it server-side at request time.
-- ============================================================================
CREATE OR REPLACE PACKAGE pkg_stripe AUTHID DEFINER AS

    -- ------------------------------------------------------------------------
    -- create_payment_link
    -- Creates a Stripe Payment Link (POST /v1/payment_links) for
    -- p_order_id with two line items -- the order's confirmed service (at
    -- its snapshotted ORDERS.SERVICE_PRICE) and Return Shipping (at
    -- ORDERS.RETURN_SHIPPING_FEE) -- and metadata.order_id set to
    -- p_order_id (so the Stripe webhook handler, TASK-032, can resolve the
    -- order from the event without any other lookup). Stores the returned
    -- link id on ORDERS.STRIPE_PAYMENT_LINK_ID and returns the link's
    -- checkout URL (needed once, immediately, for email #2 -- TASK-031 --
    -- and not persisted anywhere else, since Stripe can always be asked
    -- for it again by id).
    --
    -- Requires the order to already be priced (ORDERS.SERVICE_PRICE and
    -- RETURN_SHIPPING_FEE both set -- i.e. pkg_pricing.price_order has
    -- already run for it) and to have a SERVICE_ID -- raises -20090/-20091
    -- otherwise.
    --
    -- TASK-031: also requires ORDERS.STATUS to currently be 'Awaiting
    -- Payment' -- raises -20096 otherwise. This is this task's own
    -- acceptance criteria ("pkg_stripe.create_payment_link refuses an
    -- order in any other status"), checked here rather than only relying
    -- on pkg_order_status being this function's sole real-world caller, so
    -- the guarantee holds for a direct call too (e.g. from SQL Workshop, or
    -- a future admin action that calls this package without going through
    -- change_status). Checked before the idempotent branch below, so even
    -- a REPEATED call for an order that has since moved on (e.g. to
    -- Payment Received after the customer already paid) is refused rather
    -- than quietly re-returning the old link's URL.
    --
    -- Idempotent within Awaiting Payment: if ORDERS.STRIPE_PAYMENT_LINK_ID
    -- is already set for this order, no new link is created -- the
    -- existing link's current URL is re-fetched from Stripe and returned
    -- instead (TASK-031's "a repeated call does not create a second link"
    -- requirement holds even called directly, not only through the caller
    -- pkg_order_status.change_status uses).
    --
    -- On any Stripe API failure (network error, non-2xx response, or a 2xx
    -- response missing id/url), the failure is written to APP_ERROR_LOG
    -- (in its own autonomous transaction, so the log entry survives even
    -- if the caller's transaction is rolled back after the exception this
    -- raises) and re-raised as -20092/-20093 with a readable message.
    -- ------------------------------------------------------------------------
    FUNCTION create_payment_link(p_order_id IN NUMBER) RETURN VARCHAR2;

    -- ------------------------------------------------------------------------
    -- get_payment_link_status
    -- Reads back the Payment Link already created for p_order_id (GET
    -- /v1/payment_links/{id}) and returns 'ACTIVE' or 'INACTIVE' based on
    -- Stripe's own "active" flag on the Payment Link object -- this is
    -- whether the link itself is still usable, NOT whether the order has
    -- been paid (payment completion arrives via the webhook, TASK-032/033,
    -- not by polling this). Mainly a verification/diagnostic entry point:
    -- proving the create -> read round-trip works end-to-end against
    -- Stripe test mode is this task's own acceptance criterion.
    --
    -- Raises -20090 for an unknown ORDER_ID, -20094 if the order has no
    -- payment link yet, or -20092 on a Stripe API failure (see
    -- create_payment_link).
    -- ------------------------------------------------------------------------
    FUNCTION get_payment_link_status(p_order_id IN NUMBER) RETURN VARCHAR2;

    -- ------------------------------------------------------------------------
    -- handle_event
    -- TASK-032/033. Called by database/ords/stripe_webhook.sql's POST
    -- handler for every Stripe webhook delivery, with the raw request body
    -- (p_payload, exactly as Stripe sent it -- signature verification needs
    -- the UNMODIFIED bytes, so the ORDS module must not re-serialize or
    -- reformat it) and the raw Stripe-Signature request header
    -- (p_signature_header). Never raises -- every outcome, including a
    -- malformed request, is reported back through p_status_code/
    -- p_response_body so the ORDS handler can set the HTTP response
    -- without its own exception handling.
    --
    -- TASK-033 (checked first, before ANY database write):
    --   1. p_signature_header must be present and parse into a t= (unix
    --      timestamp) and at least one v1= (hex HMAC-SHA256 signature)
    --      field.
    --   2. Its HMAC-SHA256 (hand-built via STANDARD_HASH/UTL_RAW, key = APP_SETTING.
    --      STRIPE_WEBHOOK_SECRET) over "<t>.<raw body>" must match the v1=
    --      value.
    --   3. t= must be within c_timestamp_tolerance_seconds (see pkb) of the
    --      current time, so a captured request can't be replayed
    --      indefinitely.
    --   A missing header, an unparseable header, a mismatched signature, an
    --   unconfigured webhook secret, or a stale timestamp all fail
    --   verification the same way: p_status_code := 400, nothing is written
    --   to the database (TASK-033 acceptance criteria: "returns 400 and
    --   changes nothing").
    --
    -- TASK-032/033 (once signature verification passes):
    --   4. The event's own id (JSON $.id) is inserted into STRIPE_EVENT,
    --      whose UNIQUE (event_id) constraint makes a retried/duplicate
    --      Stripe delivery a no-op -- caught as DUP_VAL_ON_INDEX and
    --      answered with a plain 200 (Stripe stops retrying), no
    --      reprocessing.
    --   5. Only $.type = 'checkout.session.completed' (how a paid Stripe
    --      Payment Link surfaces to a webhook) is acted on -- every other
    --      event type is still recorded in STRIPE_EVENT (for audit) but
    --      otherwise ignored, answered 200 (TASK-032 acceptance criteria:
    --      "ignores unknown event types").
    --   6. For that event type, the order is resolved from
    --      $.data.object.metadata.order_id (the metadata
    --      create_payment_link, TASK-030, put on the Payment Link and that
    --      Stripe carries onto the Checkout Session it creates), ORDERS.
    --      STRIPE_PAYMENT_STATUS is updated from $.data.object.
    --      payment_status, and pkg_order_status.change_status moves the
    --      order to 'Payment Received' with p_changed_by => 'SYSTEM' (this
    --      task's acceptance criteria).
    --   7. Any failure resolving the order or advancing its status
    --      (unresolvable order_id, an order already past Payment Received,
    --      ...) is logged to APP_ERROR_LOG and swallowed -- the response is
    --      still 200, since the event itself was validly received and
    --      recorded (STRIPE_EVENT.PROCESSED stays 'N'); the alternative
    --      (a non-2xx response) would just make Stripe retry the same
    --      delivery forever for a problem retrying can't fix.
    --
    -- Responds quickly by design (TASK-032 acceptance criteria): every step
    -- above is a handful of single-row lookups/updates and one CPU-bound
    -- HMAC computation, no external calls.
    -- ------------------------------------------------------------------------
    PROCEDURE handle_event(
        p_payload           IN  CLOB,
        p_signature_header  IN  VARCHAR2,
        p_status_code        OUT PLS_INTEGER,
        p_response_body        OUT VARCHAR2
    );

END pkg_stripe;
/
